GET http://localhost:4000/api/institute
Content-Type: application/json

{
    "Id": "88",
    "fullName":"Mahendra",
    "contact":8686889337,
    "email":"mahendrakumar350@gmail.com",
    "password":"login123"
}